name: Frontend CI Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use node js 18
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run lint
        run: |
          cd starter/frontend
          npm run lint

  test:
    needs: lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node js 18
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run lint
        run: |
          cd starter/frontend
          npm run test

  build:
    needs: [lint, test]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node js 18
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run lint
        run: |
          cd starter/frontend
          npm run build
